// Generated by typings
// Source: https://acasolla:Password1@oneit.wba.com:57199/versioncontrol/projects/RXRARCHEXP/repos/rxkmobile/browse/src/ts/rxkms.d.ts?at=develop&raw
declare namespace category {

    
    class Type{
        name:string;
        subtypes:Array<string>;
    }
   
}
